# File generated by github.com/posener/goaction. DO NOT EDIT.


FROM golang:1.16-alpine3.14
RUN apk add git 

COPY . /home/src
WORKDIR /home/src
RUN go build -o /bin/action ./

ENTRYPOINT [ "/bin/action" ]
