#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Cloudflare cutover — tarlton.info to Workers"
printf '%s  Move tarlton.info from GitHub Pages to Cloudflare Workers Static Assets.\n' "$DIM"
printf '%s  Repo prep is already committed (wrangler.jsonc, wrangler devDep, _headers).\n' "$DIM"
printf '%s  Run this from the repo root. Stages 1-4 touch nothing live; stage 5 is the switch.%s\n\n' "$RESET"

# ── Stage 1: wrangler login + first deploy to workers.dev ─────────────────
stage "Wrangler login + first deploy to workers.dev"
say "First we deploy the site manually to your workers.dev subdomain."
say "This proves the whole pipeline works before anything public changes."
step "Run:  npx wrangler login"
note "A browser tab opens for Cloudflare OAuth — approve it."
pause "Press Enter after wrangler login succeeds"
step "Now deploy:  npx wrangler deploy"
note "This uploads public/ as static assets. First run may take a minute."
pause "Press Enter after the deploy succeeds"
say "Wrangler printed a URL like  https://tarlton-info.<you>.workers.dev"
ask WORKERS_DEV_URL "Paste that workers.dev URL:"
write_env WORKERS_DEV_URL "$WORKERS_DEV_URL"
say "Open it and click around: the landing page, /research/, /wiki/, and a"
say "legacy link like /NER_2025 (should redirect into /research/ner-2025/)."
open_url "$WORKERS_DEV_URL"
confirm "Does the site look right on workers.dev?" || { warn "Stop here and tell the agent what looks wrong before continuing."; exit 1; }

# ── Stage 2: connect Workers Builds (git integration) ─────────────────────
stage "Connect Workers Builds"
say "Now Cloudflare builds+deploys on every push, with PR previews for free."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Select the worker 'tarlton-info' → Settings → Builds → Connect."
step "Git repository:  michatarlton/michatarlton.github.io"
step "Production branch:  v5   (set it explicitly — do not accept a default)"
step "Build command:  npx quartz build"
step "Deploy command: leave the default (npx wrangler deploy)."
step "Enable 'Builds for non-production branches' (branch control section) —"
note "this gives every PR a preview URL + a PR comment, our review flow."
step "Add a build variable:  NODE_VERSION = 22   (Quartz needs Node ≥22)."
pause "Press Enter when the connection is saved"
say "Watch the first build it triggers in the dashboard's Builds list."
confirm "Did the first Workers Builds run succeed and deploy?" || { warn "If the build failed, paste the log to the agent before continuing."; exit 1; }

# ── Stage 3: pipeline smoke test (PR preview) ─────────────────────────────
stage "Pipeline smoke test"
say "Let's prove the review flow: a throwaway branch + PR, expecting a preview URL."
say "Run these in another terminal (or let me know if you want the agent to do it):"
step "git checkout -b test/preview && git commit --allow-empty -m 'test: preview build' && git push -u origin test/preview"
step "Open a PR for that branch on GitHub and watch for the Workers Builds comment with a preview URL."
open_url "https://github.com/MichaTarlton/michatarlton.github.io/compare"
pause "Press Enter once you saw a preview URL on the PR"
confirm "Did the preview URL work?" || { warn "Previews are required for the sync review flow — tell the agent what failed."; exit 1; }
say "You can close that PR and delete the branch (git checkout v5 && git branch -D test/preview)."

# ── Stage 4: pre-stage neuroai.wiki redirects ─────────────────────────────
stage "Pre-stage neuroai.wiki redirects"
say "neuroai.wiki becomes pure redirects — safe to set up while the site is still on GitHub Pages."
open_url "https://dash.cloudflare.com/?to=/:account/neuroai.wiki/dns/records"
step "DNS → add record:  AAAA  @  →  100::   (proxy ON, orange cloud)"
step "DNS → add record:  AAAA  www  →  100::  (proxy ON)"
open_url "https://dash.cloudflare.com/?to=/:account/neuroai.wiki/rules/redirect-rules"
step "Rules → Redirect Rules → Create rule 1:"
note "When: wildcard pattern  http*://neuroai.wiki/"
note "Then: URL  https://tarlton.info/   Status 301"
step "Create rule 2 (goes below rule 1):"
note "When: wildcard pattern  http*://neuroai.wiki/*"
note "Then: URL  https://tarlton.info/wiki/\${2}   Status 301   Preserve query string: ON"
pause "Press Enter when both rules are deployed"
say "Verify:  curl -I https://neuroai.wiki/some/page"
note "Expect: 301 with Location: https://tarlton.info/wiki/some/page"
confirm "Do the neuroai.wiki redirects work?" || { warn "Tell the agent what curl returned before continuing."; exit 1; }

# ── Stage 5: THE SWITCH ───────────────────────────────────────────────────
stage "THE SWITCH — tarlton.info to the Worker"
warn "This is the one visible step. Expect minutes of soft risk, no hard downtime."
confirm "Ready to switch tarlton.info to Cloudflare Workers?" || { say "Paused. Re-run this wizard when ready."; exit 0; }
open_url "https://dash.cloudflare.com/?to=/:account/tarlton.info/dns/records"
step "DNS → DELETE the CNAME  tarlton.info → michatarlton.github.io"
step "Also delete any www CNAME pointing at GitHub Pages, if present."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Worker 'tarlton-info' → Settings → Domains & Routes → Add → Custom Domain → tarlton.info"
note "Cloudflare creates the DNS record and issues the certificate automatically."
pause "Press Enter after the Custom Domain shows Active"
step "DNS (tarlton.info zone) → add record:  AAAA  www  →  100::  (proxy ON)"
open_url "https://dash.cloudflare.com/?to=/:account/tarlton.info/rules/redirect-rules"
step "Redirect rule: wildcard  http*://www.tarlton.info/*  →  https://tarlton.info/\${2}  301, preserve query."
pause "Press Enter when done"
say "Verify each of these now (run them in another terminal):"
step "curl -I https://tarlton.info/            → 200, server: cloudflare"
step "curl -I https://www.tarlton.info/        → 301 to https://tarlton.info/"
step "curl -I https://tarlton.info/NER_2025    → 200 (legacy stub) then refresh works"
step "curl -I https://neuroai.wiki/research/   → 301 to https://tarlton.info/wiki/research/"
open_url "https://tarlton.info/"
confirm "Is tarlton.info serving the new site from Cloudflare?" || { warn "Rollback: delete the Custom Domain, re-add the CNAME → michatarlton.github.io. Then tell the agent."; exit 1; }

# ── Stage 6: decommission GitHub Pages + final checks ─────────────────────
stage "Decommission GitHub Pages + final checks"
open_url "https://github.com/MichaTarlton/michatarlton.github.io/settings/pages"
step "Remove the custom domain 'tarlton.info' and save."
step "Disable Pages (Source: None)."
note "This stops GitHub's cert renewals and DNS-check emails."
pause "Press Enter when done"
say "Final sweep:"
step "curl -I https://tarlton.info/sitemap.xml   → 200"
step "curl -I https://tarlton.info/index.xml     → 200"
step "curl -I https://tarlton.info/nope-404/     → 404 with the Quartz 404 page"
step "Optional: Cloudflare dashboard → Web Analytics → add tarlton.info"
note "One click, auto-injected on the proxied zone; Plausible stays primary."
confirm "All green?" || { warn "Tell the agent which check failed."; exit 1; }
# ──────────────────────────────────────────────────────────────────────────

finish
